package schoolerp;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class studentFee extends javax.swing.JFrame {

    Connection con;
    Boolean saved;
    
    public studentFee() {
        try {
            initComponents();
            this.setLocation(365,115);
            con = new dbConnection().returnCon();
            saved = false;
        } catch (SQLException ex) {
            Logger.getLogger(studentFee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void getNames(Connection g) throws SQLException{
        String names = "SELECT * FROM SCHOOL.students WHERE ADMNO = '"+this.txtAdmNo.getText()+"'";
        
        String fullnames = null;
        
        Statement stmt = g.createStatement();
        ResultSet rst = stmt.executeQuery(names);
        
        while(rst.next()){
            fullnames = rst.getString("FIRSTNAME");
            fullnames = fullnames + " " + rst.getString("THIRDNAME");
        }
        
        if ("".equals(fullnames)){
            JOptionPane.showMessageDialog(null,"There is no student with the provided Admission Number");
            this.txtAdmNo.setText("");
        }else{
            this.txtName.setText(fullnames);
        }
    }
    
    private void getFee(Connection f)throws SQLException{
        String fee = "SELECT * FROM SCHOOL.feeStructure WHERE FORM = ? ";     
        String term = this.cboTerm.getSelectedItem().toString();
        double amount = 0;
        
        PreparedStatement pstmt = f.prepareStatement(fee);
        pstmt.setString(1,this.cboForm.getSelectedItem().toString());
        
        ResultSet rst = pstmt.executeQuery();
        
        while (rst.next()){
            if(this.cboTerm.getSelectedIndex()==0){
                amount = rst.getDouble("TERM1");
            }else if (this.cboTerm.getSelectedIndex()==1){
                amount = rst.getDouble("TERM2");
            }else{
                amount = rst.getDouble("TERM3");
            }
        }
        this.txtEFee.setText(String.valueOf(amount));
        
    }
    
    private void saveTransaction(Connection t)throws SQLException{
        String saving = "INSERT INTO SCHOOL.fee (ADMNO,STUDENTNAME,FORM,TERM,AMOUNTPAID,"
                + "BALANCE,OVERPAYMENT) VALUES (?,?,?,?,?,?,?)";
        String adm = this.txtAdmNo.getText();
        String name = this.txtName.getText();
        String form = this.cboForm.getSelectedItem().toString();
        String term = this.cboTerm.getSelectedItem().toString();
        double paid = 0;
        double balance = 0;
        double overpayment = 0;
        try {
            paid = Double.parseDouble(this.txtPaid.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null,"Amount Paid is a value don't input letters");
        }
        double expected = Double.parseDouble(this.txtEFee.getText());
        if (expected > paid){
            balance = expected -paid;
            overpayment = 0;
        }else if (expected<paid){
            balance = 0;
            overpayment = paid - expected;
        }
        
        PreparedStatement pstmt = t.prepareStatement(saving);
        
        pstmt.setString(1, adm);
        pstmt.setString(2,name);
        pstmt.setString(3, form);
        pstmt.setString(4,term);
        pstmt.setDouble(5, paid);
        pstmt.setDouble(6, balance);
        pstmt.setDouble(7,overpayment);
        
        pstmt.executeUpdate();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtAdmNo = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        cboForm = new javax.swing.JComboBox();
        cboTerm = new javax.swing.JComboBox();
        txtEFee = new javax.swing.JTextField();
        txtPaid = new javax.swing.JTextField();
        txtBal = new javax.swing.JTextField();
        txtOver = new javax.swing.JTextField();
        btnNew = new javax.swing.JButton();
        btnReceipt = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("FEE PAYMENT DETAILS");

        jLabel2.setText("Admission Number");

        jLabel3.setText("Names");

        jLabel4.setText("FORM");

        jLabel5.setText("Expected Fee");

        jLabel6.setText("Amount Paid");

        jLabel7.setText("Term");

        jLabel8.setText("Outstanding Balance");

        jLabel9.setText("Overpayment");

        txtAdmNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAdmNoFocusLost(evt);
            }
        });

        txtName.setEditable(false);

        cboForm.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "FORM 1", "FORM 2", "FORM 3", "FORM 4" }));

        cboTerm.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "FIRST", "SECOND", "THIRD", " " }));
        cboTerm.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboTermItemStateChanged(evt);
            }
        });

        txtEFee.setEditable(false);

        txtPaid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPaidFocusLost(evt);
            }
        });

        txtBal.setEditable(false);

        txtOver.setEditable(false);

        btnNew.setText("New");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnReceipt.setText("View Receipt");
        btnReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReceiptActionPerformed(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtName)
                                    .addComponent(cboForm, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cboTerm, 0, 145, Short.MAX_VALUE)
                                    .addComponent(txtEFee)
                                    .addComponent(txtPaid)
                                    .addComponent(txtBal)
                                    .addComponent(txtOver)
                                    .addComponent(txtAdmNo)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(btnReceipt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(26, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAdmNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cboForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboTerm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEFee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPaid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtBal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtOver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNew)
                    .addComponent(btnReceipt)
                    .addComponent(btnExit))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAdmNoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAdmNoFocusLost
        try {
            getNames(con);
        } catch (SQLException ex) {
            Logger.getLogger(studentFee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtAdmNoFocusLost

    private void cboTermItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboTermItemStateChanged
        try{
            getFee(con);
        }catch(SQLException ex){
            Logger.getLogger(studentFee.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_cboTermItemStateChanged

    private void btnReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReceiptActionPerformed
       if (saved ==false){
            try {
                saveTransaction(con);
                saved =true;
            } catch (SQLException ex) {
                Logger.getLogger(studentFee.class.getName()).log(Level.SEVERE, null, ex);
            }
       }
    }//GEN-LAST:event_btnReceiptActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        if (saved ==false){
            try {
                saveTransaction(con);
                saved = true;
            } catch (SQLException ex) {
                Logger.getLogger(studentFee.class.getName()).log(Level.SEVERE, null, ex);
            }
       }
       new studentFee().setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
       new admin().setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_btnExitActionPerformed

    private void txtPaidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPaidFocusLost
        double paid = 0;
        double balance = 0;
        double overpayment = 0;
        try {
            paid = Double.parseDouble(this.txtPaid.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null,"Amount Paid is a value don't input letters");
        }
        double expected = Double.parseDouble(this.txtEFee.getText());
        if (expected > paid){
            balance = expected -paid;
            overpayment = 0;
        }else if (expected<paid){
            balance = 0;
            overpayment = paid - expected;
        }
        this.txtBal.setText(String.valueOf(balance));
        this.txtOver.setText(String.valueOf(overpayment));
    }//GEN-LAST:event_txtPaidFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentFee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentFee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentFee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentFee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new studentFee().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnReceipt;
    private javax.swing.JComboBox cboForm;
    private javax.swing.JComboBox cboTerm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtAdmNo;
    private javax.swing.JTextField txtBal;
    private javax.swing.JTextField txtEFee;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtOver;
    private javax.swing.JTextField txtPaid;
    // End of variables declaration//GEN-END:variables
}
