package schoolerp;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class studentClass extends javax.swing.JFrame {

    Connection con;
    DefaultTableModel mode = null;
    int count;
    
    public studentClass() {
        try {
            initComponents();
            this.setLocation(100,75);
            mode = (DefaultTableModel)this.jtblClass.getModel();
            con = new dbConnection().returnCon();
             getClasses(con);
        } catch (SQLException ex) {
            Logger.getLogger(studentClass.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void getClasses(Connection c)throws SQLException{
        String klasName;
        String klas = "SELECT * FROM SCHOOL.classes";
        
        Statement stmtKlas = c.createStatement();
        ResultSet rstKlas = stmtKlas.executeQuery(klas);
        
        while(rstKlas.next()){
            klasName = rstKlas.getString("CLASSNAME");
            this.cboClass.addItem(klasName);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cboClass = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblClass = new javax.swing.JTable();
        btnOK = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Select Class");

        jtblClass.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Admission No", "First Name", "Middle Name", "Last Name", "Guardian Names", "Residence", "Address", "Phone No", "Dorm", "Sport"
            }
        ));
        jtblClass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtblClassKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jtblClass);
        jtblClass.getColumnModel().getColumn(0).setResizable(false);
        jtblClass.getColumnModel().getColumn(1).setResizable(false);
        jtblClass.getColumnModel().getColumn(2).setResizable(false);
        jtblClass.getColumnModel().getColumn(3).setResizable(false);
        jtblClass.getColumnModel().getColumn(4).setResizable(false);
        jtblClass.getColumnModel().getColumn(4).setPreferredWidth(100);
        jtblClass.getColumnModel().getColumn(5).setResizable(false);
        jtblClass.getColumnModel().getColumn(6).setResizable(false);
        jtblClass.getColumnModel().getColumn(7).setResizable(false);
        jtblClass.getColumnModel().getColumn(8).setResizable(false);
        jtblClass.getColumnModel().getColumn(9).setResizable(false);

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(cboClass, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1131, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnExit)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExit))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        try {
            storeStudents(con);
            new students().setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(studentClass.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnOKActionPerformed

    private void jtblClassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtblClassKeyPressed
        if (evt.getKeyCode() == 10) { //When enter is pressed            
            addRow();            
        } else if (evt.getKeyCode() == 127) { //when delete is pressed
            delete();            
        }
    }//GEN-LAST:event_jtblClassKeyPressed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        new students().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnExitActionPerformed

    private void addRow() {               
        mode.addRow(new Object[]{null}); 
    }
    private void delete() {
        mode.removeRow(jtblClass.getSelectedRow());
    }
    
    private void storeStudents(Connection p) throws SQLException{
        String adm ;
        String first;
        String middle;
        String last;
        String guardian;
        String residence;
        String address;
        String contact;
        String dorm;
        String sport;
        String klass = this.cboClass.getSelectedItem().toString();
        
        
        String saving = "INSERT INTO SCHOOL.students (ADMNO,GUARDIANNAMES,RESIDENCE,"
                + "ADDRESS,CONTACTNO,FIRSTNAME,SECONDNAME,THIRDNAME,THECLASS,THEDORM,"
                + "SPORT) VALUES(?,?,?,?,?,?,?,?,?,?,?)";
        PreparedStatement pstmt = p.prepareStatement(saving);
        
        count = mode.getRowCount();
        
        for(int i = 0; i < count; i++){
            adm = (String) mode.getValueAt(i,0);
            first = (String) mode.getValueAt(i,1);
            middle = (String) mode.getValueAt(i,2);
            last = (String) mode.getValueAt(i,3);
            guardian = (String) mode.getValueAt(i,4);
            residence = (String) mode.getValueAt(i,5);
            address = (String) mode.getValueAt(i,6);
            contact = (String) mode.getValueAt(i,7);
            dorm = (String) mode.getValueAt(i,8);
            sport = (String) mode.getValueAt(i,9);
            
            
            pstmt.setString(1,adm);
            pstmt.setString(2,guardian);
            pstmt.setString(3,residence);
            pstmt.setString(4,address);
            pstmt.setString(5,contact);
            pstmt.setString(6,first);
            pstmt.setString(7,middle);
            pstmt.setString(8,last);
            pstmt.setString(9,klass);
            pstmt.setString(10,dorm);
            pstmt.setString(11,sport);
            
            int exec = pstmt.executeUpdate();
            
            if (exec == 0){
                JOptionPane.showMessageDialog(null,"Saving Error occurred please try again");
                break;                
            }
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new studentClass().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnOK;
    private javax.swing.JComboBox cboClass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtblClass;
    // End of variables declaration//GEN-END:variables
}
