package installationPackage;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class feeStructure extends javax.swing.JFrame {

    DefaultTableModel mode;
    
    public feeStructure() {
        initComponents();
        this.setLocation(430,250);
        mode = (DefaultTableModel)jtblFee.getModel();
        enterForms();
    }

    private void enterForms(){
        mode.setValueAt((Object)"FORM 1", 0,0);
        mode.setValueAt((Object)"FORM 2", 1,0);
        mode.setValueAt((Object)"FORM 3", 2,0);
        mode.setValueAt((Object)"FORM 4", 3,0);     
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblFee = new javax.swing.JTable();
        btnNext = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("FILL THE FEE VALUE STURUCTURE FOR THE DIFFERENT FORMS");

        jtblFee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "FORM", "TERM 1", "TERM 2", "TERM 3"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtblFee);
        jtblFee.getColumnModel().getColumn(0).setResizable(false);
        jtblFee.getColumnModel().getColumn(1).setResizable(false);
        jtblFee.getColumnModel().getColumn(2).setResizable(false);
        jtblFee.getColumnModel().getColumn(3).setResizable(false);

        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNext, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        try {
            saveFee();
            setInstalled();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "All fields must be field");
        }
        
        new complete().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnNextActionPerformed

    private void saveFee() throws SQLException{
        Connection p = new dbConnection().returnCon();
        
        String fee = "INSERT INTO SCHOOL.feeStructure (FORM,TERM1,TERM2,TERM3) VALUES(?,?,?,?)";
        
        PreparedStatement pstmt = p.prepareStatement(fee);
        String form;
        double term1 = 0;
        double term2= 0;
        double term3 =0;
        
        for (int i = 0; i < mode.getRowCount(); i++){
            form = (String)mode.getValueAt(i,0);
            term1 = (Double)mode.getValueAt(i,1);
            if(term1 == 0)
                continue;
            term2 = (Double)mode.getValueAt(i,2);
            if(term2 == 0)
                continue;
            term3 = (Double)mode.getValueAt(i,3);
            if(term3 == 0)
                continue;
            
            pstmt.setString(1,form);
            pstmt.setDouble(2, term1);
            pstmt.setDouble(3,term2);
            pstmt.setDouble(4, term3);
            
            pstmt.executeUpdate();
        }
                
    }
    private void setInstalled()throws SQLException{
        Connection p = new dbConnection().returnCon();
        String installed = "UPDATE SCHOOL.installed SET VERIFY = ? WHERE VERIFY ='yet' ";
        String value = "Done";
        PreparedStatement pstmt = p.prepareStatement(installed);
        pstmt.setString(1, value);
        
        pstmt.executeUpdate();        
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(feeStructure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(feeStructure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(feeStructure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(feeStructure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new feeStructure().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtblFee;
    // End of variables declaration//GEN-END:variables
}
