package installationPackage;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class subjects extends javax.swing.JFrame {

    DefaultTableModel mode = null;
    String currentSubject;
    
    public subjects() {
        initComponents();
        this.setLocation(300,150);
        mode = (DefaultTableModel) this.jtblnames.getModel();
        currentSubject = "English";
        this.txtSub.setText(currentSubject);
    }

    private void nextSubject(String sub){
        
        if ("English".equals(sub)){
            currentSubject = "Kiswahili";
        }else if ("Kiswahili".equals(sub)){
            currentSubject = "Mathematics";
        }else if ("Mathematics".equals(sub)){
            currentSubject = "Geography";
        }else if ("Geography".equals(sub)){
            currentSubject = "History";
        }else if ("History".equals(sub)){
            currentSubject = "CRE";
        }else if ("CRE".equals(sub)){
            currentSubject = "Physics";
        }else if ("Physics".equals(sub)){
            currentSubject = "Chemistry";
        }else if ("Chemistry".equals(sub)){
            currentSubject = "Biology";
        }else if ("Biology".equals(sub)){
            currentSubject = "Business";
        }else if ("Business".equals(sub)){
            currentSubject = "Computer";
        }else if ("Computer".equals(sub)){
            currentSubject = "ART";
        }else if ("ART".equals(sub)){
            currentSubject = "PE";
        }else if ("PE".equals(sub)){
            currentSubject = "MetalWork";
        }else if ("MetalWork".equals(sub)){
            currentSubject = "Music";
        }
        txtSub.setText(currentSubject);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblnames = new javax.swing.JTable();
        txtSub = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ENTER A TEACHERS NAME AND THEN TICK THE FORM HE/SHE TEACHES");

        btnNext.setText("Next Subject");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        jtblnames.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "TEACHER NAME", "TEACHES FORM 1", "TEACHES FORM 2", "TEACHES FORM 3", "TEACHES FORM 4"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jtblnames.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtblnamesKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jtblnames);
        jtblnames.getColumnModel().getColumn(0).setPreferredWidth(220);

        txtSub.setEditable(false);
        txtSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnNext)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(txtSub, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        if("Music".equals(currentSubject)){
            save();            
            new feeStructure().setVisible(true);
            this.setVisible(false);            
        }else{
           save();
           clearTable();
           nextSubject(currentSubject);
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void jtblnamesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtblnamesKeyPressed
        if (evt.getKeyCode() == 10) { //When enter is pressed            
            addRow();
        } else if (evt.getKeyCode() == 127) { //when delete is pressed
            delete();
        } 
    }//GEN-LAST:event_jtblnamesKeyPressed

    private void addRow() {               
        mode.addRow(new Object[]{null}); 
    }
    private void delete() {
        mode.removeRow(jtblnames.getSelectedRow());
    }
    
    private void txtSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubActionPerformed

    private void save(){
        try {
            String saving = "INSERT INTO SCHOOL.subjects "
                    + "(SUBJECT,TEACHERNAME,FORM1,FORM2,FORM3,FORM4) VALUES(?,?,?,?,?,?)";
                    
            dbMethod(saving);
            
        } catch (SQLException ex) {
            Logger.getLogger(subjects.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    public void dbMethod(String sql) throws SQLException{
        Connection p = new dbConnection().returnCon();
        
        PreparedStatement pstmt = p.prepareStatement(sql);
        
        String tname = null;
        Boolean form1;
        Boolean form2;
        Boolean form3;
        Boolean form4;
        
        int count = mode.getRowCount();
        
        for(int i = 0; i < count; i++){
            
            
            tname = (String) mode.getValueAt(i,0);
            if(tname == null)
                continue;
            form1 = (Boolean) mode.getValueAt(i,1);
            if(form1 ==null)
                form1 = false;
            form2 = (Boolean) mode.getValueAt(i,2);
            if(form2 ==null)
                form2 = false;
            form3= (Boolean) mode.getValueAt(i,3);
            if(form3 ==null)
                form3 = false;
            form4 = (Boolean) mode.getValueAt(i,4);
            if(form4 ==null)
                form4 = false;
            
            pstmt.setString(1,currentSubject);
            pstmt.setString(2,tname);
            pstmt.setBoolean(3,form1);
            pstmt.setBoolean(4,form2);
            pstmt.setBoolean(5,form3);
            pstmt.setBoolean(6,form4);
            
            int exec = pstmt.executeUpdate();
            
            if (exec == 0){
                JOptionPane.showMessageDialog(null,"Saving Error occurred please try again");
                break;                
            }
        }
    }
    private void clearTable(){
        int count = mode.getRowCount()-1;
        for(int i = 0; i < count;i++){
            mode.removeRow(0);
        }
        mode.setValueAt((Object)"",0,0);
        mode.setValueAt((Boolean)false, 0,1);
        mode.setValueAt((Boolean)false, 0,2);
        mode.setValueAt((Boolean)false, 0,3);
        mode.setValueAt((Boolean)false, 0,4);        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(subjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(subjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(subjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(subjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new subjects().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtblnames;
    private javax.swing.JTextField txtSub;
    // End of variables declaration//GEN-END:variables
}
